# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20181018_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
