# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20181018_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_message',
            new_name='parentMessage',
        ),
    ]
